export const GET_CHOCOLATE ="GET_CHOCOLATE";
export const GET_CHOCOLATE_SUCCESS ="GET_CHOCOLATE_SUCCESS";
export const GET_CHOCOLATE_FAILURE ="GET_CHOCOLATE_FAILURE";

export const GET_BRAND ="GET_BRAND";
export const GET_BRAND_SUCCESS ="GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE ="GET_BRAND_FAILURE";

export const CHANGE_INPUT = "CHANGE_INPUT";

export const GET_USER ="GET_USER";
export const GET_USER_SUCCESS ="GET_USER_SUCCESS";
export const GET_USER_FAILURE ="GET_USER_FAILURE";

export const GET_CHOCOLATEBYBRAND="GET_CHOCOLATEBYBRAND";
export const GET_CHOCOLATEBYBRAND_SUCCESS="GET_CHOCOLATEBYBRAND_SUCCESS";
export const GET_CHOCOLATEBYBRAND_FAILURE="GET_CHOCOLATEBYBRAND_FAILURE";

export const GET_LOGIN ="GET_LOGIN";
export const GET_LOGIN_SUCCESS ="GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE ="GET_LOGIN_FAILURE";

export const GET_SEARCH ="GET_SEARCH";
export const GET_SEARCH_SUCCESS ="GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILURE ="GET_SEARCH_FAILURE";

export const GET_LOGOUT ="GET_LOGOUT";

